Html Post Form
AshwinCarvalho999/Portfolio-Mobile-Form pull request #1
Opened 2022-08-23 14:07 UTC by AshwinCarvalho999

Added index.html
Added style.css
Added Linters
Created an HTML form to get the details of the user or to connect with the user using Formspree
Added .gitignore file to ignore node_modules file
Added Readme file

2022-08-23 14:53 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @AshwinCarvalho999, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Good use of GitHub flow. ✔️
 - Style looks almost identical to Figma template. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 14:53 UTC, leonardodiasb commented on index.html
> +        ></textarea>
- [ ] Great implementation of the form. But it seems that you forgot to require the message field. Please validate the `<textarea>` so the user cannot submit the form if any input field is empty as the project requires.
 -
<img width="561" alt="image" src="https://user-images.githubusercontent.com/61919617/186190262-d7b1cad4-11eb-4a54-a52c-bf5a0ad46aa8.png">

2022-08-24 07:06 UTC, muneebulrehman approved these changes
Hi @AshwinCarvalho999 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Good design
- Good follow-up with the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 07:29 UTC, AshwinCarvalho999 commented
Thanks for the feedback!

On Wed, Aug 24, 2022, 12:36 PM MUNEEB UL REHMAN ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @AshwinCarvalho999 <https://github.com/AshwinCarvalho999> ,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it 🥳
> Congratulations! 🎉
> Status: Approved✔️ Highlights
>
>    - No linter errors
>    - Good design
>    - Good follow-up with the previous reviewer.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AshwinCarvalho999/Portfolio-Mobile-Form/pull/1#pullrequestreview-1083266686>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVKQBYSCMJ4KYL3UXE457ETV2XCWHANCNFSM57LUQYPQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-08-24 07:34 UTC, merged